baseURL = 'https://oudwalvisch.nl/'
title = 'Oud Walvisch'
theme = 'PaperMod'

defaultContentLanguage = 'nl'
languageCode = 'nl'

[params]
  # Site metadata
  description = "Website van Oud Walvisch"
  
  # Theme settings
  defaultTheme = "light"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  
  # Home page settings
  homeInfoParams = {
    Title = "Welkom bij Oud Walvisch 🏊‍♂️",
    Content = "Een historische zwemvereniging in WAT"
  }

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
    
  [[menu.main]]
    identifier = "posts"
    name = "Nieuws"
    url = "/posts/"
    weight = 20
