baseURL = "https://jelmerkk.github.io/oudwalvisch.nl/"
title = "Stichting Oud Walvisch"
theme = ["PaperMod"]
defaultContentLanguage = "nl"
languageCode = "nl"

params:
  description: Website van de Stichting Oud Walvisch
  defaultTheme: light
  ShowBreadCrumbs: false
  header: true
  header_image: /images/header-desktop-mockup.png
  assets:
    css:
      - css/custom.css
  homeInfoParams: {}
  disableThemeToggle: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: over-ons
      name: Over Ons
      url: /over-ons/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: gszc
      name: Moederdier
      url: https://www.gszcdewalvisch.nl
      weight: 30
      params:
        target: _blank
    - identifier: donateur
      name: Donateur worden
      url: /aanmelden/
      weight: 40
