baseURL = "https://oudwalvisch.nl/"
title = "Oud Walvisch"
theme = "PaperMod"
defaultContentLanguage = "nl"
languageCode = "nl"

[params]
  description = "Website van Oud Walvisch"
  defaultTheme = "light"
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "Welkom bij Oud Walvisch 🏊‍♂️"
  Content = "De Stichting Oud Walvisch is ...."

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10
    
[[menu.main]]
  identifier = "over-ons"
  name = "Over Ons"
  url = "/over-ons/"
  weight = 20

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 30
